name: kernel build  CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send Initiation Message
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=Markdown" \
        -d text="\`CI\` Build for [${GITHUB_SHA}](https://github.com/stormbreaker-project/kernel_realme_sdm660/commit/${GITHUB_SHA}) initiated at *$(TZ=Asia/Kolkata date)*"
    - uses: actions/checkout@v1
    - name: Build kernel
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        git clone -b rebase https://github.com/stormbreaker-project/kernel_realme_sdm660
        export CROSS_COMPILE=${PWD}/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export KBUILD_BUILD_USER="iamsaalim"
        export ARCH=arm64
        export CROSS_COMPILE_ARM32=${PWD}/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
        export SUBARCH=arm64
        #export DTC_EXT=dtc
        #chmod a+x /home/runner/work/iamsaalim/kernel_realme_sdm660/scripts/dtc/bin/dtc
        #PATH="clang/bin:aarch64-linux-android-4.9/bin:aarch64-linux-android-4.9/bin:/home/runner/work/iamsaalim/kernel_realme_sdm660/scripts/dtc/bin:${PATH}"
        #mkdir clang
        #wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/39e7c63aa6239ae92d63913c82bbe1e9e44b4013/clang-r370808.tar.gz
        #tar -C clang -xvzf clang-r*.tar.gz
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/
        make -j12 O=out RMX1801_defconfig
        make -j12 O=out 
        if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
          cp out/arch/arm64/boot/Image.gz-dtb flasher/Image.gz-dtb
          cd flasher
          zip -r9 "StormbreakerKernel-KernelCI.zip" * -x .git README.md LICENSE
          cp StormbreakerKernel-KernelCI.zip ..
          cd ..
          tod="$(TZ=Asia/Kolkata date +'%Y%m%d-%H%M')"
          cp flasher/StormbreakerKernel-KarnulCI.zip "StormbreakerKernel-CI-$tod.zip"
          curl --progress-bar -F document=@"StormbreakerKernel-CI-$tod.zip" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
         -F chat_id="${CHAT_ID}"  \
         -F "disable_web_page_preview=true" \
         -F "parse_mode=Markdown" \
         -F caption="Build for [${GITHUB_SHA}](https://github.com/stormbreaker-project/kernel_realme_sdm660/commit/${GITHUB_SHA}) succeeded at: *$(TZ=Asia/Kolkata date)* \`|\` Flashable zip attached"     
        else
          cat error.log | grep -i -A3 error > build_error.txt
          curl --progress-bar -F document=@"build_error.txt" "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
          -F chat_id="${CHAT_ID}"  \
          -F "disable_web_page_preview=true" \
          -F "parse_mode=Markdown" \
          -F caption="Build for [${GITHUB_SHA}](https://github.com/stormbreaker-project/kernel_realme_sdm660/commit/${GITHUB_SHA}) failed at: *$(TZ=Asia/Kolkata date)* \`|\` Trimmed error log attached"  
        fi
    - uses: actions/upload-artifact@v1.0.0
      name: Artifact-ify Bleed
      with:
        name: CIKarnulBleed
        path: CrimsonKernel-KarnulCI.zip
